# 产品或项目名称
productName: FastOs Demo

server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    servlet:
        context-path: /fast
    #ssl:
    #   key-store: classpath:
    #   key-store-type: PKCS12
    #   key-store-password: ''
    #开启springBoot 对输出页面进行压缩
    compression:
        enabled: true
        mime-types: 'application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain'
spring:
    # 环境 Dev|Test|Prod
    profiles:
        active: Dev
    servlet:
        multipart:   #设置上传文件大小
            max-file-size: 200MB  #单个文件的大小
            max-request-size: 200MB  #单次请求的文件的总大小
            enabled: true
    freemarker:
        suffix: .html
        request-context-attribute: request
        #cache: false
    # 资源信息
    messages:
        # 国际化资源文件路径
        basename: i18n/i18n
        enabled: false
        #默认语言（4.1.3+）
        defaultLocale: zh_CN
framework:
    redis:
        open: true  # 是否开启redis缓存  true开启   false关闭
        name: stk   #监控中redis中名称
    shiro:
        redis: false # true表示shiro session存到redis里，需要开启redis，才会生效【分布式场景】
# Shiro
shiro:
    cookie:
        # 设置Cookie的域名 默认空，即当前访问的域名
        domain:
        # 设置HttpOnly属性
        httpOnly: true
        # 设置Cookie的过期时间，天为单位
        maxAge: 30
    session:
        # Session超时时间，-1代表永不过期（默认30分钟）
        expireTime: 30
        #设置session失效的扫描时间, 清理用户直接关闭浏览器造成的孤立会话 (默认设置5分钟)
        validationTime: 5
#mybatis
mybatis-plus:
    mapper-locations: classpath*:mapper/**/*.xml
    global-config:
        banner: false
        #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
        id-type: ASSIGN_ID
        #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
        field-strategy: 2
        #驼峰下划线转换
        db-column-underline: true
        #刷新mapper 调试神器
        refresh-mapper: true
        #数据库大写下划线转换
        capital-mode: true
        # Sequence序列接口实现类配置
        #key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
        #逻辑删除配置
        logic-delete-value: '1'
        logic-not-delete-value: '0'
        #自定义SQL注入器
        #sql-injector: com.baomidou.mybatisplus.core.injector.ISqlInjector
    configuration:
        map-underscore-to-camel-case: true
        cache-enabled: false
        call-setters-on-nulls: true
#日志
logging:
    path: logs/
    file: fast.log